<font color="green">To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.</font>

# Python Programming:  Simple Random Sampling


## Importing our Libraries

In [ ]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [ ]:
# Example 1
# ---
# Selecting more than one item from a list 
# ---
#

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=3))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [120, 20, 100]
Choosing 3 random items from a list using sample function [40, 20, 20]


### <font color="green"> 1.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.
# ---
# 
counties = ['Mombasa', 'Kwale', 'Kilifi', 'Tana River', 'Lamu.', 'Taita/Taveta', 'Garissa.', 'Wajir']
print ('Random county pair:', random.sample(counties, k=2))

Random county pair: ['Lamu.', 'Garissa.']


## 2.0  Selecting the Random Sample from Dictionary

In [ ]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('Kelly', 55), ('Donald', 60)]


### <font color="green">2.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 
# ---
#
food_packages = {'bronze_package' : {'starch':'rice', 'stew':'chicken curry', 'vegetable':'cabbages', 'desert':'melon'},
                 'silver_package' : {'starch':'rice and chappati',  'stew':'beef curry', 'vegetable':'spinach', 'desert':'melon and bananas'},
                 'gold_package': {'starch':'rice, chappati and mukimo', 'stew': 'beef curry', 'vegetable':'spinach and managu', 'desert': 'tart'}
}
print (random.sample(food_packages.items(), k=2))


[('gold_package', {'starch': 'rice, chappati and mukimo', 'stew': 'beef curry', 'vegetable': 'spinach and managu', 'desert': 'tart'}), ('silver_package', {'starch': 'rice and chappati', 'stew': 'beef curry', 'vegetable': 'spinach', 'desert': 'melon and bananas'})]


## 3.0 Selecting a Random Sample with Replacement to including repetition


In [ ]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below
# ---
# 
names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Andre', 'Nadal', 'Mariya']


### <font color="green">3.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']

print('random months with replacement to include repetition', random.choices(months, k=3))

random months with replacement to include repetition ['June', 'May', 'September']


## 4.0 Selecting a Random Sample from a Range of Integers

In [ ]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [65, 55, 80, 75]


### <font color="green">4.1 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}

print('chosing 3 random samples from the range of interges', random.sample(weight_set, k=3))

chosing 3 random samples from the range of interges [10, 8, 4]


## 5.0 Selecting a Sample Array from a Large multidimensional Array



In [ ]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[ 7 14 21]
[ 6 12 18]


### <font color="green">5.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

a = np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]]  )

print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(7, size=2)
for i in randomRows:
  print(a[i,:])

Selecting multiple random rows from the 2D array
[1 2 4 5 6]
[ 4  8 12 16 20]


## 6.0 Selecting Random Samples from a Dataset

In [ ]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

(110527, 14)
      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]
           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
79067   4.361176e+12        5651850      M  ...       0            0       No
2469    3.211434e+13        5619655      M  ...       0            1       No
41975   9.229387e+13        5653645      F  ...       1            0      Yes
96012   2.617658e+12        5757093      M  ...       0            0       No
109467  5.569557e+12        5760451      F  ...       0            0       No
43295   9.977995e+12        5660166      M  ...       0   

### <font color="green">6.0 Challenges </font>

In [ ]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
# Dataset url = http://bit.ly/DSRussianInvestigation
# ---
#
url ='http://bit.ly/DSRussianInvestigation'
df = pd.read_csv(url)
print (df.shape)
print(df.head())

# random sample of 10
df = df.sample(n=10, replace= False)
print (df.shape)
print(df)

(194, 13)
  investigation investigation-start  ... american      president
0     watergate          1973-05-19  ...     True  Richard Nixon
1     watergate          1973-05-19  ...     True  Richard Nixon
2     watergate          1973-05-19  ...     True  Richard Nixon
3     watergate          1973-05-19  ...     True  Richard Nixon
4     watergate          1973-05-19  ...     True  Richard Nixon

[5 rows x 13 columns]
(10, 13)
                     investigation  ...         president
91                     iran-contra  ...     Ronald Reagan
9                        watergate  ...     Richard Nixon
10                       watergate  ...     Richard Nixon
113  sealed-investigation-hwbush-2  ...  George H.W. Bush
188                         russia  ...      Donald Trump
149                       cisneros  ...      Bill Clinton
36                       watergate  ...     Richard Nixon
13                       watergate  ...     Richard Nixon
66                       watergate  ...     Ri

In [ ]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
#
url = 'http://bit.ly/MedicalAppointmentsDataset'
med_df = pd.read_csv(url)
print(med_df.shape)

# Selecting the ones who were a no-show and received an SMS
med_dfc = med_df[(med_df['SMS_received'] == 1) & (med_df['No-show'] == 'Yes')]
print(med_dfc.shape)

# Random sample of 50
med_dfc = med_dfc.sample(n=50, replace=False)
print('The shape of the random sample sample: ', med_dfc.shape)
print(med_dfc) 

(110527, 14)
(9784, 14)
The shape of the random sample sample:  (50, 14)
           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
22384   5.898452e+12        5640625      M  ...       0            1      Yes
84908   5.752660e+13        5738136      F  ...       0            1      Yes
36128   4.797911e+13        5618954      F  ...       0            1      Yes
105700  3.235148e+10        5763206      F  ...       0            1      Yes
26282   3.431287e+14        5461012      F  ...       0            1      Yes
38403   7.583267e+11        5608759      F  ...       0            1      Yes
104849  7.894552e+14        5717062      F  ...       0            1      Yes
79213   4.929853e+13        5629912      F  ...       0            1      Yes
82072   9.286654e+09        5614277      F  ...       0            1      Yes
51991   2.329912e+13        5700382      F  ...       0            1      Yes
19443   8.264823e+14        5624438      F  ...       0            1 